<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>NationRise.Bench</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NationRise.Core\NationRise.Core.csproj" />
  </ItemGroup>

</Project>
