<Project Sdk="Godot.NET.Sdk/4.7.0">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NationRise.Game</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sim\NationRise.Core\NationRise.Core.csproj" />
  </ItemGroup>

</Project>
